### PR TITLE
Simplify count of characters by leveraging Java 8 syntax

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by mattrpav** [comment]
Hey @apupier thanks for the contribution. As a process heads up-- we are getting close to being done w/ the big swath refactoring and should be 100% operating out of github within a week or so. 

I'm merging this here, and in our active repo so it'll come across in the next merge downs. If you have more changes like this, it might make sense to make tickets or hold off until we get our big swath in so we can avoid big merge pains until we are 100% running out of here.

Thanks =)

**Comment by mattrpav** [comment]
BTW-- parking this PR for a bit.

I tried merging this, but it blows up b/c IntStream returns long instead of int (method signature)

**Comment by apupier** [comment]
> I tried merging this, but it blows up b/c IntStream returns long instead of int (method signature)

sorry i did that too quickly during a train trip. my bad.

What is the best?
- change method return type to long?
- cast to int?

cast to int is changing no behavior, change method to long allows to support longer String handling but does it have other impact?

**Comment by mattrpav** [comment]
I think we should convert to using 'long' as the return type in the method

**Comment by igarashitm** [comment]
@apupier any news on this one?

**Comment by igarashitm** [comment]
attempting close&reopen to rerun circleci/codacy

**Comment by igarashitm** [comment]
closing abandoned

**Pull request closed without merging**
